# 0 dimensional

In [1]:
import numpy as np
my_array= np.array(50)
print(my_array)

50


In [3]:
import numpy as sp
my_value= sp.array(40)
print(my_value)


40


# 1 dimensional

In [4]:
import numpy as tp
my_value= tp.array([22,23,13,21])
print(my_value)

[22 23 13 21]


In [9]:
my_value= tp.array([22,273.,12,1])
print(my_value)

[ 22. 273.  12.   1.]


# 2 dimensional

In [ ]:
import numpy as cd
my_value= cd.array([12,43,22,43],[13,53,43,76])


In [16]:
import numpy as cd
my_array = cd.array([[10,20,30]])
my_array

array([[10, 20, 30]])

In [17]:
my_array.ndim

2